### ISSUE TITLE
Add flash message to the top of the form when success or error when submitting

### ISSUE THREAD

**Issue by michaelbmuller** [alaseif/DOE-Cloned#3]

**Comment by michaelbmuller** [comment]
Ala, don't close the issues until the associated updated code has been
committed to the git repo. Otherwise it looks like issue has been resolved
in the current committed version of the code which I'm assuming it hasn't.
Thanks Mike

**Comment by alaseif** [comment]
I’m sorry, Just did commit. I’m still working on the gallery .. hope I can finish it tonight
